# Generated by Django 4.2.11 on 2025-10-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_big_comment_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Item',
        ),
    ]
