# Generated by Django 4.2.11 on 2025-10-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_listing_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Big',
            new_name='Bid',
        ),
    ]
