# Generated by Django 4.2.11 on 2025-10-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_big_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auctions.item'),
        ),
    ]
