# Generated by Django 4.2.11 on 2025-10-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='start_bid',
            new_name='bid_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='image_url',
        ),
    ]
