# Generated by Django 4.2.11 on 2025-10-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_bid_item_bid_bid_user_bid_user_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='max_bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
