# Generated by Django 4.2.11 on 2025-10-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_max_bid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='max_bid_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
