# Generated by Django 4.2.11 on 2025-10-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_max_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
