# Generated by Django 4.2.11 on 2025-10-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_item_current_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
