# Generated by Django 4.2.11 on 2025-10-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_item_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='onpost',
            field=models.BooleanField(default=True),
        ),
    ]
