# Generated by Django 4.2.11 on 2025-10-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_item_onpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_bidder',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
