# Generated by Django 4.2.11 on 2025-10-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_item_current_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_log', to='auctions.item'),
        ),
    ]
