# Generated by Django 4.2.11 on 2025-10-11 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_comment_commentary_comment_commented_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
